#!/usr/bin/env python3
"""Single source of truth for the Embed.Art identity.

Every committed SVG is emitted from here, so the mark's geometry cannot drift
between logo.svg, wordmark.svg, icon.svg and preview.svg: there is only one
copy of it, in MARK_* below.

Type outlines live in outlines.json, regenerated by make_outlines.py whenever
the copy or the type spec changes. This file never needs a font.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------- palette
ACCENT = "#BE8F04"          # the art in the slot. Exactly one thing wears this.
INK_LIGHT = "#1A1A1A"       # default ink when the SVG is opened on its own
INK_DARK = "#F5DEB3"        # wheat, as already used across the site
PLATE = "#111111"           # the site's background
MUTED = "#8E826A"           # wheat at ~55% over the plate, for the tagline

# ------------------------------------------------------------- mark (K3)
# 256 box. Ink box is x/y 30..226, i.e. 196 square, centred.
MARK_BOX = 256.0
MARK_INK = 196.0
MARK_INK_ORIGIN = 30.0
MARK_STROKE = 28.0
MARK_OPENING = 140.0        # between the inside faces of the arms: 58..198
GUEST = 100.0               # the gold square's side
GUEST_RX = 12.0
BRACKET_L = "M78 44 H44 V212 H78"
BRACKET_R = "M178 44 H212 V212 H178"

# Icon cut: same drawing, heavier stroke and a wider opening so the brackets
# still hold ~2px at 16px. This is the SIMPLIFICATION, not a scaled logo.
ICON_STROKE = 34.0
ICON_BRACKET_L = "M78 42 H42 V214 H78"
ICON_BRACKET_R = "M178 42 H214 V214 H178"
ICON_GUEST_RX = 13.0
ICON_INK = 206.0            # 42-17 .. 214+17
ICON_INK_ORIGIN = 25.0

# --------------------------------------------------------------- lockup
LOCKUP_GAP = 56.0           # mark ink box to wordmark ink box, in mark units
WORD_INK_H = MARK_OPENING   # the wordmark is exactly as tall as the slot

# ----------------------------------------------------------------- card
# The card must carry the APPROVED lockup, not a re-proportioned copy of it, so
# the mark-to-wordmark ratio here is whatever the lockup already fixed (1.4).
# Only the lockup's overall width is chosen; everything else follows.
CARD_W, CARD_H = 1280.0, 640.0
CARD_LOCKUP_W = 1080.0      # leaves a 100px side margin
CARD_TAG_INK_W = 520.0
CARD_RULE = (120.0, 6.0)
CARD_GAP_RULE = 48.0        # lockup ink bottom -> rule top
CARD_GAP_TAG = 34.0         # rule bottom -> tagline ink top


def outlines():
    with open(os.path.join(HERE, "outlines.json")) as fh:
        return json.load(fh)


def _svg(w, h, body, ink=INK_LIGHT, extra=""):
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w:g} {h:g}"'
        f' width="{w:g}" height="{h:g}" style="color: {ink}"{extra}>\n'
        f"{body}\n</svg>\n"
    )


def mark_body(stroke, left, right, guest_rx, accent=ACCENT):
    return (
        f'  <g fill="none" stroke="currentColor" stroke-width="{stroke:g}"'
        ' stroke-linecap="butt" stroke-linejoin="miter">\n'
        f'    <path d="{left}"/>\n'
        f'    <path d="{right}"/>\n'
        '  </g>\n'
        f'  <rect x="78" y="78" width="{GUEST:g}" height="{GUEST:g}"'
        f' rx="{guest_rx:g}" fill="{accent}"/>'
    )


def glyphs(key, scale, tx, ty, fill="currentColor", indent="  "):
    """Place an outline set. Path data is in make_outlines.py's probe space, so
    the text origin is subtracted here rather than baked into the `d` strings.
    tx/ty position the text ORIGIN; callers derive them from o["ink"], which is
    already relative to that origin."""
    o = outlines()[key]
    ox, oy = o["origin"]
    paths = "\n".join(
        f'{indent}  <path d="{d}"/>' for d in o["paths"]
    )
    return (
        f'{indent}<g transform="translate({tx:.4f} {ty:.4f}) scale({scale:.6f})'
        f' translate({-ox:g} {-oy:g})" fill="{fill}">\n{paths}\n{indent}</g>'
    )


# ------------------------------------------------------------------ files
def logo_svg():
    """The mark alone. currentColor ink, no background."""
    return _svg(MARK_BOX, MARK_BOX,
                mark_body(MARK_STROKE, BRACKET_L, BRACKET_R, GUEST_RX))


def wordmark_svg(ink=INK_LIGHT):
    """Mark + wordmark, text outlined. Ink box is flush with the viewBox."""
    o = outlines()["wordmark"]
    scale = WORD_INK_H / o["ink"][3]
    tx = MARK_INK + LOCKUP_GAP - o["ink"][0] * scale
    ty = MARK_INK / 2.0 - (o["ink"][1] + o["ink"][3] / 2.0) * scale
    w = MARK_INK + LOCKUP_GAP + o["ink"][2] * scale
    body = (
        f'  <g transform="translate({-MARK_INK_ORIGIN:g} {-MARK_INK_ORIGIN:g})">\n'
        f'{mark_body(MARK_STROKE, BRACKET_L, BRACKET_R, GUEST_RX)}\n  </g>\n'
        f'{glyphs("wordmark", scale, tx, ty)}'
    )
    return _svg(round(w, 2), MARK_INK, body, ink=ink)


def icon_svg():
    """Simplified mark on an opaque plate: a transparent icon with dark ink
    disappears on a dark browser tab."""
    rx = MARK_BOX * 0.18
    scale = (MARK_BOX * 0.86) / ICON_INK
    off = (MARK_BOX - ICON_INK * scale) / 2.0 - ICON_INK_ORIGIN * scale
    body = (
        f'  <rect width="{MARK_BOX:g}" height="{MARK_BOX:g}" rx="{rx:g}" fill="{PLATE}"/>\n'
        f'  <g transform="translate({off:.4f} {off:.4f}) scale({scale:.6f})"'
        f' style="color: {INK_DARK}">\n'
        f'{mark_body(ICON_STROKE, ICON_BRACKET_L, ICON_BRACKET_R, ICON_GUEST_RX)}\n'
        '  </g>'
    )
    return _svg(MARK_BOX, MARK_BOX, body, ink=INK_DARK)


def icon_bare_svg():
    """Transparent, no plate: what the maskable generator must be fed, so the
    result is not a box inside a box."""
    scale = (MARK_BOX * 0.86) / ICON_INK
    off = (MARK_BOX - ICON_INK * scale) / 2.0 - ICON_INK_ORIGIN * scale
    body = (
        f'  <g transform="translate({off:.4f} {off:.4f}) scale({scale:.6f})">\n'
        f'{mark_body(ICON_STROKE, ICON_BRACKET_L, ICON_BRACKET_R, ICON_GUEST_RX)}\n'
        '  </g>'
    )
    return _svg(MARK_BOX, MARK_BOX, body, ink=INK_DARK)


def preview_svg():
    """1280x640 card: og:image, twitter summary_large_image, GitHub social
    preview, all without cropping. Centred stack, so the lockup stays the hero
    and keeps the exact proportions it was approved at."""
    o = outlines()
    wm, tag = o["wordmark"], o["tagline"]

    # the lockup, scaled as one piece
    word_scale_in_lockup = WORD_INK_H / wm["ink"][3]
    lockup_w = MARK_INK + LOCKUP_GAP + wm["ink"][2] * word_scale_in_lockup
    s = CARD_LOCKUP_W / lockup_w
    mark_scale = s
    word_scale = word_scale_in_lockup * s
    lockup_h = MARK_INK * s

    tag_scale = CARD_TAG_INK_W / tag["ink"][2]
    tag_h = tag["ink"][3] * tag_scale

    stack_h = lockup_h + CARD_GAP_RULE + CARD_RULE[1] + CARD_GAP_TAG + tag_h
    top = (CARD_H - stack_h) / 2.0
    x0 = (CARD_W - CARD_LOCKUP_W) / 2.0

    mark_x = x0 - MARK_INK_ORIGIN * mark_scale
    mark_y = top - MARK_INK_ORIGIN * mark_scale
    word_x = x0 + (MARK_INK + LOCKUP_GAP) * s - wm["ink"][0] * word_scale
    word_y = top + lockup_h / 2.0 - (wm["ink"][1] + wm["ink"][3] / 2.0) * word_scale

    rule_y = top + lockup_h + CARD_GAP_RULE
    rule_x = (CARD_W - CARD_RULE[0]) / 2.0
    tag_x = (CARD_W - CARD_TAG_INK_W) / 2.0 - tag["ink"][0] * tag_scale
    tag_y = rule_y + CARD_RULE[1] + CARD_GAP_TAG - tag["ink"][1] * tag_scale

    return _svg(CARD_W, CARD_H, "\n".join([
        '  <defs>',
        '    <radialGradient id="glow" cx="0.18" cy="0.82" r="0.62">',
        f'      <stop offset="0" stop-color="{ACCENT}" stop-opacity="0.16"/>',
        f'      <stop offset="1" stop-color="{ACCENT}" stop-opacity="0"/>',
        '    </radialGradient>',
        '  </defs>',
        f'  <rect width="{CARD_W:g}" height="{CARD_H:g}" fill="{PLATE}"/>',
        f'  <rect width="{CARD_W:g}" height="{CARD_H:g}" fill="url(#glow)"/>',
        # No motif texture: the stack fills the card, so faint marks in the
        # corners had to be cropped by the edge and read as glitches, not
        # texture. The glow alone carries the depth.
        f'  <g transform="translate({mark_x:.4f} {mark_y:.4f}) scale({mark_scale:.6f})"'
        f' style="color: {INK_DARK}">',
        mark_body(MARK_STROKE, BRACKET_L, BRACKET_R, GUEST_RX),
        '  </g>',
        glyphs("wordmark", word_scale, word_x, word_y, fill=INK_DARK),
        f'  <rect x="{rule_x:.4f}" y="{rule_y:.4f}" width="{CARD_RULE[0]:g}"'
        f' height="{CARD_RULE[1]:g}" fill="{ACCENT}"/>',
        glyphs("tagline", tag_scale, tag_x, tag_y, fill=MUTED),
    ]), ink=INK_DARK)


FILES = {
    "logo.svg": logo_svg,
    "wordmark.svg": wordmark_svg,
    # An <img> or a GitHub README cannot pass currentColor into an SVG, so the
    # dark-ink cut has to exist as its own file. Same geometry, one colour.
    "wordmark-dark.svg": lambda: wordmark_svg(ink=INK_DARK),
    "icon.svg": icon_svg,
    "icon-bare.svg": icon_bare_svg,
    "preview.svg": preview_svg,
}

if __name__ == "__main__":
    import sys
    check = "--check" in sys.argv
    bad = []
    for name, fn in FILES.items():
        path = os.path.join(HERE, name)
        new = fn()
        if check:
            old = open(path).read() if os.path.exists(path) else None
            if old != new:
                bad.append(name)
        else:
            with open(path, "w") as fh:
                fh.write(new)
            print("wrote", name)
    if check:
        if bad:
            print("error: generated SVGs differ from spec.py: " + ", ".join(bad))
            sys.exit(1)
        print("ok: all generated SVGs match spec.py")
